---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  default.server: |
    IMMUNOPLEX_HOSTNAME {
        hosts {
              IMMUNOPLEX_IP_ADDRESS IMMUNOPLEX_HOSTNAME
              fallthrough
        }
    }
